module.exports = {
	USER_USERNAME_LENGTH: 20,
	USER_AVATAR_URL_LENGTH: 255,
	USER_NAME_LENGTH: 80,
	TOPIC_SLUG_LENGTH: 20,
	TOPIC_DESCRIPTION_LENGTH: 255,
	ARTICLE_TITLE_LENGTH: 255,
	COMMENT_BODY_LENGTH: 5000,
};